export const LAYER_Z_INDEX = Object.freeze({
  BASE_MAP: 200,
  GARS: 300,
  // Airspace / nav layers — bottom to top matches desired chart render order
  AIRSPACE_ALERT: 410,
  AIRSPACE_MOA: 420,
  AIRSPACE_RESTRICTED: 430,
  AIRSPACE_SIMULATED: 440,
  IFR_LOW: 445,
  IFR_HIGH: 450,
  NAVAIDS: 455,
  AIRSPACE_CLASS_D: 460,
  AIRSPACE_CLASS_C: 470,
  AIRSPACE_CLASS_B: 480,
  AIRFIELDS: 490,
  DRAWINGS: 500,
  UI_OVERLAY: 900,
});

export const PANE_IDS = Object.freeze({
  BASE_MAP: 'pane-base-map',
  GARS: 'pane-gars',
  AIRSPACE_ALERT: 'pane-airspace-alert',
  AIRSPACE_MOA: 'pane-airspace-moa',
  AIRSPACE_RESTRICTED: 'pane-airspace-restricted',
  AIRSPACE_SIMULATED: 'pane-airspace-simulated',
  IFR_LOW: 'pane-ifr-low',
  IFR_HIGH: 'pane-ifr-high',
  NAVAIDS: 'pane-navaids',
  AIRSPACE_CLASS_D: 'pane-airspace-class-d',
  AIRSPACE_CLASS_C: 'pane-airspace-class-c',
  AIRSPACE_CLASS_B: 'pane-airspace-class-b',
  AIRFIELDS: 'pane-airfields',
  DRAWINGS: 'pane-drawings',
});

export const ORDERED_STACK = Object.freeze([
  PANE_IDS.BASE_MAP,
  PANE_IDS.GARS,
  PANE_IDS.AIRSPACE_ALERT,
  PANE_IDS.AIRSPACE_MOA,
  PANE_IDS.AIRSPACE_RESTRICTED,
  PANE_IDS.AIRSPACE_SIMULATED,
  PANE_IDS.IFR_LOW,
  PANE_IDS.IFR_HIGH,
  PANE_IDS.NAVAIDS,
  PANE_IDS.AIRSPACE_CLASS_D,
  PANE_IDS.AIRSPACE_CLASS_C,
  PANE_IDS.AIRSPACE_CLASS_B,
  PANE_IDS.AIRFIELDS,
  PANE_IDS.DRAWINGS,
]);
